base:
  project_name: slmt_Demo
  ckpt_root: ./ckpt
  seed: 8
  lr: 0.0001
  weight_decay: 0.0001
  batch_size: 64
  n_epochs: 200
  num_workers: 8
  gpu_id: 1

dataset:
  datasetName: sims
  dataPath: /workspace/datasets/MSA_Datasets/SIMS/unaligned_39.pkl 
  train_mode: regression

model:  
  model_type: base
  bert_pretrained: bert-base-chinese

  
  l_input_dim: 768
  a_input_dim: 33
  v_input_dim: 709
  l_proj_dst_dim: 128
  a_proj_dst_dim: 128
  v_proj_dst_dim: 128

 
  token_len: 8
  token_dim: 128
  l_input_length: 39
  a_input_length: 400
  v_input_length: 55
  proj_input_dim: 128
  proj_depth: 1
  proj_heads: 8
  proj_mlp_dim: 128

  token_length: 8
  l_enc_heads: 8
  l_enc_mlp_dim: 128

  
  SLL_depth: 3
  SLL_heads: 8
  SLL_dim_head: 16
  SLL_droup: 0.

 
  fusion_heads: 8
  fusion_mlp_dim: 128
  fusion_layer_depth: 4
